
[packages.Cython]
version = "0.29.27"

[packages.debugpy]
version = "1.5.1"

[packages.numpy]
version = "1.22.2"
build_pip_requirements = ["Cython==0.29.26"]
cross_pip_requirements = ["robotpy-openblas-dev"]
install_requirements = ["robotpy-openblas"]

[packages.numpy.environment]
F77 = "arm-frc2022-linux-gnueabi-gfortran"
F90 = "arm-frc2022-linux-gnueabi-gfortran"
# As of NumPy 1.22.0, a vendored copy of SVML will be built on x86_64 Linux
# hosts to provide AVX-512 acceleration of floating-point operations. When
# using an x86_64 Linux build system to cross compile NumPy for hosts other
# than x86_64 Linux, set the environment variable NPY_DISABLE_SVML to prevent
# the NumPy build script from incorrectly attempting to cross-compile this
# platform-specific library:
NPY_DISABLE_SVML = "1"

[packages.ptvsd]
version = "4.3.2"

[packages.pydevd]
version = "2.7.0"

[packages.pyinstrument_cext]
version = "0.2.4"

[packages."PyYAML"]
version = "6.0"

# TODO
# [packages.scipy]
# version = "1.5.3"

[packages."zope.interface"]
version = "5.4.0"

[packages.websockets]
version = "10.3"
